### ISSUE TITLE
SAM Local

### ISSUE THREAD

**Issue by e-moshaya** [Girija-Shankar-Swain/html-to-pdf-generator-puppeteer-aws-lambda#4]
Hi,

I'm trying to test this locally.. I ran the following:

`sam local start-api --env-vars sam-local-env.json`

How do I pass a json body with the url to test the generate pdf function? I keep getting "Missing Authentication Token"

**Comment by GSSwain** [comment]
Thanks for raising the issue.

You need to pass the url in the request body. 

Example:

```
curl -i -X POST \
  http://127.0.0.1:3000/generate-pdf/ \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -d '{
 "url": "<ReplaceWIthYourURLHere>"
}'
```

You can find more Information [here](https://gsswain.medium.com/serverless-pdf-generation-from-html-wysiwyg-as-pdf-2f295a23cb6d). I'll update the `README` later.
